name: Get Kaggle Dataset

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
        with:
          ref: ${{ github.HEAD_REF || github.REF_NAME }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get dataset
        shell: python
        run: |
          import kaggle
          api = kaggle.api
          path = 'yjh4374/sisvse-dataset/data/images/real'
          api.authenticate
          api.dataset_download_files(path, './dataset', force=True)

      - name: Push dataset
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am 'Push dataset'
          git push
