name: Get Kaggle Dataset

on: workflow_dispatch

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
        with:
          ref: ${{ github.HEAD_REF || github.REF_NAME }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Get dataset
        shell: python
        run: |
          import opendatasets as od
          url = 'https://www.kaggle.com/datasets/yjh4374/sisvse-dataset/data'
          od.download(url, './images/real')

      - name: Push dataset
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am 'Push dataset'
          git push
