name: Get Kaggle Dataset

on: workflow_dispatch

env:
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_KEY }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_USERNAME }}

jobs:
  fetch:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v4
        with:
          ref: ${{ github.HEAD_REF || github.REF_NAME }}

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r ./docs/requirements.txt

      - name: Get dataset
        shell: python
        run: |
          import kaggle
          api = kaggle.api
          path = 'yjh4374/sisvse-dataset'
          api.authenticate
          api.dataset_download_files(path, './src')

      - name: Push dataset
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A && git commit -am 'Push dataset'
          git push
